server:
  port: 8000
  servlet:
    context-path: /v0.1

spring:
  application:
    name: skyhawks-authentication-service
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/login
    username: ananthupm
    password: Password
  jpa:
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://127.0.0.1:9411/

app:
  service:
    authenticate-user: true
    validate-user: true
