server:
  port: 8000
  servlet:
    context-path: /v0.1

spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://database-1.cc33tfhdinqi.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Aw5Pa$$wo6d
  jpa:
    hibernate:
      ddl-auto: none

app:
  service:
    authenticate-user: true
    validate-user: true
    notification-service-url: http://notification-service:9000/v0.1
    school-service-url: http://school-service:1000/v0.1