server:
  port: 8050
  servlet:
    context-path: /v0.1

spring:
  application:
    name: skyhawks-notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: skyhawks.app@gmail.com
    password: nuvldcdnuafzcbxv
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
  zipkin:
    base-url: http://127.0.0.1:9411/


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka