server:
  port: 8100
  servlet:
    context-path: /v0.1

spring:
  application:
    name: skyhawks-school-service
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://database-1.cc33tfhdinqi.ap-south-1.rds.amazonaws.com:5432/dev-school-01
    username: postgres
    password: Aw5Pa$$wo6d
  jpa:
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://127.0.0.1:9411/

app:
  service:
    authenticate-user: true
    validate-user: true

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka